//! Law-merged Nash curriculum — first concrete curriculum landing on
//! the §6 SDF stack (Skill registry + Verdict union + cycle combinator).
//!
//! Categorical anchor:
//!   `goblins-adapter/propagator-nash.scm:140` — `merge-with-law`:
//!     `Merge × Law → Merge'`.
//!   Wraps a base merge so any law-violating outcome promotes to a
//!   contradiction. Here the merge IS the cycle's Step (which mutates
//!   agent state) and the law is GF(3) closure on the strategy trits.
//!
//! Setup:
//!   - N agents each carry an i48 `state` interpreted as their proposed
//!     strategy. Their body just echoes that state (the topology runs;
//!     the evaluator is satisfied by an always-positive scorer; the
//!     point of the curriculum is the inter-iteration STEP, not the
//!     evaluator output).
//!
//!   - The `lawMergeStep` body collects every agent's `(state mod 3)`
//!     trit, checks GF(3) closure (sum ≡ 0 mod 3). If the law holds,
//!     it's a no-op (the topology has reached a Nash-stable lawful
//!     point). If violated, it nudges the last agent's state +1; this
//!     is guaranteed to land on a lawful triad within ≤2 nudges for
//!     three agents (the cyclic group GF(3) is generated by +1).
//!
//! That is the SDF-permanent-extension promise paying off:
//!   - Step.custom (§6.3) gives us the structural mutation hook.
//!   - The curriculum lives in its own file with no edits to feedback.zig
//!     / cycle.zig / experiment.zig.
//!   - Adding ProTeGi-coplay or Solo-MAGICORE later follows the same
//!     pattern: another submodule, another `*Step.body` closure.

const std = @import("std");
const value = @import("../value.zig");
const Value = value.Value;

const agent_lib = @import("agent.zig");
const eval_lib = @import("eval.zig");
const dataset_lib = @import("dataset.zig");
const experiment_lib = @import("experiment.zig");
const topology_lib = @import("topology.zig");
const trace_lib = @import("trace.zig");
const cycle_lib = @import("cycle.zig");

const Topology = topology_lib.Topology;
const Experiment = experiment_lib.Experiment;
const Report = experiment_lib.Report;

/// Project an agent's i48 state to a GF(3) trit ∈ {-1, 0, +1}, matching
/// `Verdict.trit`'s `i2` convention. `state mod 3 = 2` collapses onto
/// `-1` since `2 ≡ -1 (mod 3)` in the GF(3) signed representation.
pub fn stateToTrit(state: ?Value) i2 {
    const s: i48 = if (state) |v| v.asInt() else 0;
    const m: i48 = @mod(s, 3); // 0, 1, or 2
    return switch (m) {
        0 => 0,
        1 => 1,
        2 => -1,
        else => unreachable,
    };
}

/// GF(3) closure check: sum of trits ≡ 0 (mod 3).
pub fn lawHolds(trits: []const i2) bool {
    var sum: i32 = 0;
    for (trits) |t| sum += @as(i32, t);
    return @mod(sum, 3) == 0;
}

/// The `cycle.Step.custom.body` for this curriculum.
/// Reads every agent's state, projects to GF(3) trit, checks the law;
/// if violated, nudges the last agent's state by +1 to walk toward
/// closure. (No-op when already lawful — that's the fixed point.)
pub fn lawMergeStep(experiment: *Experiment, _: *const Report) anyerror!void {
    const topo = experiment.topology;
    const n = topo.nodes.items.len;
    if (n == 0) return;

    var trits: std.ArrayListUnmanaged(i2) = .empty;
    defer trits.deinit(experiment.allocator);
    for (topo.nodes.items) |*node| {
        try trits.append(experiment.allocator, stateToTrit(node.agent.state));
    }
    if (lawHolds(trits.items)) return;

    const last = &topo.nodes.items[n - 1].agent;
    const cur: i48 = if (last.state) |v| v.asInt() else 0;
    last.state = Value.makeInt(cur + 1);
}

// ─────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────

fn echoStateBody(ctx: *agent_lib.Agent, _: Value) error{Invoke}!Value {
    if (ctx.state) |s| return s;
    return Value.makeInt(0);
}

fn alwaysPositiveScorer(_: Value) eval_lib.EvalError!f32 {
    return 1.0;
}

test "stateToTrit: null → 0; 1 → 1; 5 → -1 (2≡-1); 9 → 0" {
    try std.testing.expectEqual(@as(i2, 0), stateToTrit(null));
    try std.testing.expectEqual(@as(i2, 1), stateToTrit(Value.makeInt(1)));
    try std.testing.expectEqual(@as(i2, -1), stateToTrit(Value.makeInt(5)));
    try std.testing.expectEqual(@as(i2, 0), stateToTrit(Value.makeInt(9)));
}

test "lawHolds: 1+1+1 ≡ 0 (mod 3)" {
    const trits = [_]i2{ 1, 1, 1 };
    try std.testing.expect(lawHolds(&trits));
}

test "lawHolds: 0+0+0 ≡ 0" {
    const trits = [_]i2{ 0, 0, 0 };
    try std.testing.expect(lawHolds(&trits));
}

test "lawHolds: 0+1+(-1) ≡ 0 (≡ 0+1+2 in unsigned mod-3)" {
    const trits = [_]i2{ 0, 1, -1 };
    try std.testing.expect(lawHolds(&trits));
}

test "lawHolds: 1+1+0 ≢ 0" {
    const trits = [_]i2{ 1, 1, 0 };
    try std.testing.expect(!lawHolds(&trits));
}

fn setupThreeAgentExperiment(
    topo: *Topology,
    trace_store: *trace_lib.TraceStore,
    ds: *dataset_lib.Dataset,
    seeds: [3]i48,
) !void {
    const id_a = try topo.newAgent("a", echoStateBody);
    const id_b = try topo.newAgent("b", echoStateBody);
    const id_c = try topo.newAgent("c", echoStateBody);
    topo.nodes.items[id_a - 1].agent.state = Value.makeInt(seeds[0]);
    topo.nodes.items[id_b - 1].agent.state = Value.makeInt(seeds[1]);
    topo.nodes.items[id_c - 1].agent.state = Value.makeInt(seeds[2]);
    try ds.addExample(Value.makeInt(0), null, "");
    _ = trace_store;
}

test "law-merged Nash: balanced seed (1,1,1) is already a fixed point" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    var ds = dataset_lib.Dataset.init(std.testing.allocator, "balanced");
    defer ds.deinit();
    try setupThreeAgentExperiment(&topo, &trace_store, &ds, .{ 1, 1, 1 });

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "balanced", &topo, &trace_store, &ds, &evs, "a");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = lawMergeStep } },
        .{ .iters = 5 },
        1,
        5,
    );
    defer traj.deinit();

    // No-op step → c remains at 1.
    try std.testing.expectEqual(@as(i48, 1), topo.nodes.items[2].agent.state.?.asInt());
    // GF(3) law still holds.
    var trits: [3]i2 = undefined;
    for (topo.nodes.items, 0..) |node, i| trits[i] = stateToTrit(node.agent.state);
    try std.testing.expect(lawHolds(&trits));
}

test "law-merged Nash: imbalanced (1,0,0) converges to a lawful triad" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    var ds = dataset_lib.Dataset.init(std.testing.allocator, "imbalanced");
    defer ds.deinit();
    try setupThreeAgentExperiment(&topo, &trace_store, &ds, .{ 1, 0, 0 });

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "imbalanced", &topo, &trace_store, &ds, &evs, "a");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = lawMergeStep } },
        .{ .iters = 10 },
        1,
        10,
    );
    defer traj.deinit();

    // After enough custom-step nudges the GF(3) law holds.
    var trits: [3]i2 = undefined;
    for (topo.nodes.items, 0..) |node, i| trits[i] = stateToTrit(node.agent.state);
    try std.testing.expect(lawHolds(&trits));
    // a stayed at 1 (it's not the last agent); b stayed at 0; c was nudged.
    try std.testing.expectEqual(@as(i48, 1), topo.nodes.items[0].agent.state.?.asInt());
    try std.testing.expectEqual(@as(i48, 0), topo.nodes.items[1].agent.state.?.asInt());
    // c's trit must close the law: trits[0]=1, trits[1]=0 ⇒ trit[2]=-1
    // (equivalently, c.state mod 3 = 2).
    try std.testing.expectEqual(@as(i2, -1), stateToTrit(topo.nodes.items[2].agent.state));
}

test "law-merged Nash: imbalanced (2,2,0) converges by nudging c twice" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    var ds = dataset_lib.Dataset.init(std.testing.allocator, "twos");
    defer ds.deinit();
    try setupThreeAgentExperiment(&topo, &trace_store, &ds, .{ 2, 2, 0 });
    // a.state=2 → trit -1; b.state=2 → trit -1; c.state=0 → trit 0.
    // Sum = -2 ≡ 1 (mod 3) ≢ 0. Need c's trit such that -1 + -1 + t ≡ 0
    // ⇒ t ≡ -1. Starting c=0, two nudges → c=2 → trit -1. ✓

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "twos", &topo, &trace_store, &ds, &evs, "a");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = lawMergeStep } },
        .{ .iters = 10 },
        1,
        10,
    );
    defer traj.deinit();

    var trits: [3]i2 = undefined;
    for (topo.nodes.items, 0..) |node, i| trits[i] = stateToTrit(node.agent.state);
    try std.testing.expect(lawHolds(&trits));
    try std.testing.expectEqual(@as(i2, -1), stateToTrit(topo.nodes.items[2].agent.state));
}

// ─────────────────────────────────────────────────────────────────────
// Solo-MAGICORE curriculum — Solver/Reviewer/Refiner triad with
// step-wise PRM scoring via Verdict.vector.
//
// Reference: Sachin Kumar et al. 2024, "MAGICORE: Multi-Agent Iteration
// for Coarse-to-fine Refinement". Three-agent feedback loop where:
//   - Solver  produces a k-step reasoning chain
//   - Reviewer scores each step (PRM = process reward model)
//   - Refiner uses the per-step scores to decide which step to fix
//
// Concrete Zig encoding without an LLM:
//   - "Chain" = an i48 state interpreted as a 5-digit decimal value
//   - "PRM"   = digitwise scorer; each digit's score = digit / 9.0,
//               so high digits (closer to 9) mean "high quality step"
//   - "Refiner" = the Step.custom body that increments the
//                 lowest-scoring digit's "place value" until the chain's
//                 minimum digit clears the threshold
//
// The curriculum demonstrates Verdict.vector being constructed in
// real curriculum code and dispatched through `primaryScore()` (which
// projects the vector to its mean for legacy passes). The refiner
// reads the raw vector to do step-wise repair, not just mean-based
// gating — that's the whole point of MAGICORE over a scalar reward.
// ─────────────────────────────────────────────────────────────────────

/// Decompose an i48 chain into 5 digits, MSB first. State outside
/// [0, 99999] is clamped to [0, 99999].
pub fn chainDigits(state: ?Value) [5]u8 {
    const s_raw: i48 = if (state) |v| v.asInt() else 0;
    var s: i48 = if (s_raw < 0) 0 else if (s_raw > 99999) 99999 else s_raw;
    var out: [5]u8 = .{ 0, 0, 0, 0, 0 };
    var i: usize = 5;
    while (i > 0) {
        i -= 1;
        out[i] = @intCast(@mod(s, 10));
        s = @divFloor(s, 10);
    }
    return out;
}

/// PRM (process reward model): each digit's reward = digit / 9.0 ∈ [0, 1].
/// Returns a Verdict.vector whose `steps` borrow `out_buf` — caller owns
/// the buffer and must keep it alive while the verdict is examined.
pub fn digitwisePRM(state: ?Value, name: []const u8, out_buf: *[5]f32) eval_lib.Verdict {
    const digits = chainDigits(state);
    for (digits, 0..) |d, i| {
        out_buf[i] = @as(f32, @floatFromInt(d)) / 9.0;
    }
    return .{ .vector = .{
        .evaluator_name = name,
        .steps = out_buf[0..],
    } };
}

/// Refiner step: read the solver's current chain, score each digit
/// via the PRM, find the worst-scoring digit, and bump that place's
/// value by +1 in the i48 state. Stops being a no-op once every
/// digit's score ≥ 7/9 ≈ 0.78 (i.e., every digit is ≥ 7).
pub fn magicoreRefineStep(experiment: *Experiment, _: *const Report) anyerror!void {
    const topo = experiment.topology;
    const solver = topo.getAgent("solver") orelse return;

    var scores: [5]f32 = undefined;
    const verdict = digitwisePRM(solver.state, "prm", &scores);

    // primaryScore() = mean of vector; cycle stop predicates can use it.
    // Here we use the raw steps for the refiner decision.
    const v = verdict.vector;
    var worst_idx: usize = 0;
    var worst_score: f32 = v.steps[0];
    for (v.steps[1..], 1..) |s, i| {
        if (s < worst_score) {
            worst_score = s;
            worst_idx = i;
        }
    }
    if (worst_score >= 7.0 / 9.0) return; // already at fixed point

    // Place value of digit at index worst_idx (MSB=0): 10^(4-worst_idx).
    const place: i48 = std.math.pow(i48, 10, @intCast(4 - worst_idx));
    const cur: i48 = if (solver.state) |s| s.asInt() else 0;
    solver.state = Value.makeInt(cur + place);
}

test "chainDigits decomposes 12345 → [1,2,3,4,5]" {
    const d = chainDigits(Value.makeInt(12345));
    try std.testing.expectEqualSlices(u8, &.{ 1, 2, 3, 4, 5 }, &d);
}

test "chainDigits clamps negatives to zero, large to 99999" {
    try std.testing.expectEqualSlices(u8, &.{ 0, 0, 0, 0, 0 }, &chainDigits(Value.makeInt(-7)));
    try std.testing.expectEqualSlices(u8, &.{ 9, 9, 9, 9, 9 }, &chainDigits(Value.makeInt(123456789)));
}

test "digitwisePRM yields Verdict.vector with per-digit reward" {
    var buf: [5]f32 = undefined;
    const v = digitwisePRM(Value.makeInt(99999), "prm", &buf);
    try std.testing.expectEqualStrings("prm", v.name());
    // primaryScore is mean-of-steps; 9/9 averaged = 1.0
    try std.testing.expectApproxEqAbs(@as(f32, 1.0), v.primaryScore(), 1e-6);
    // mean of zero digits = 0
    var buf2: [5]f32 = undefined;
    const v2 = digitwisePRM(Value.makeInt(0), "prm", &buf2);
    try std.testing.expectEqual(@as(f32, 0.0), v2.primaryScore());
}

test "Solo-MAGICORE: refiner converges to all-7+ chain" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();

    _ = try topo.newAgent("solver", echoStateBody);
    _ = try topo.newAgent("reviewer", echoStateBody);
    _ = try topo.newAgent("refiner", echoStateBody);
    try topo.connect("solver", "reviewer");
    try topo.connect("reviewer", "refiner");

    // Seed: 11111 → digits [1,1,1,1,1], all scores 1/9. Worst=any; refiner
    // bumps a place each iter. Needs ~5 nudges per place × (7-1) bump =
    // 30+ iters. Give it 60 to converge.
    topo.nodes.items[0].agent.state = Value.makeInt(11111);

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "magicore");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "magicore", &topo, &trace_store, &ds, &evs, "solver");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = magicoreRefineStep } },
        .{ .iters = 60 },
        1,
        60,
    );
    defer traj.deinit();

    // After convergence, every digit of solver.state should be ≥ 7.
    const final_state = topo.nodes.items[0].agent.state.?;
    const digits = chainDigits(final_state);
    for (digits) |d| try std.testing.expect(d >= 7);
}

// ─────────────────────────────────────────────────────────────────────
// Evaluator-Optimizer curriculum — Verdict.record exercised in
// Step.custom, mirroring the mcp-agent / PraisonAI pattern.
//
// Single optimizer agent holds a "draft" state (i48 quality metric).
// Step.custom reads the latest output, constructs a Verdict.record
// containing { score, feedback }, and uses BOTH the scalar score AND
// the feedback string to decide the revision direction:
//   feedback == "OK"   → no-op (fixed point)
//   feedback == "raise"→ bump state +5  (drive score up)
//   feedback == "lower"→ bump state -5  (drive score down — used in
//                                         the overshoot recovery test)
//
// The verdict's `passes(threshold)` projects through primaryScore (=
// the record's `.score` field), so the existing scalar-threshold
// machinery still works — but the feedback string carries direction
// information that a pure scalar can't.
// ─────────────────────────────────────────────────────────────────────

/// Decide the feedback string given a normalized score.
/// OK band is [0.95, 1.05); above is "lower" (overshoot), below is "raise".
fn feedbackFor(score: f32) []const u8 {
    if (score >= 1.05) return "lower";
    if (score >= 0.95) return "OK";
    return "raise";
}

pub fn evalOptimizerStep(experiment: *Experiment, report: *const Report) anyerror!void {
    const topo = experiment.topology;
    const optimizer = topo.getAgent("optimizer") orelse return;

    if (report.examples.len == 0) return;
    const out = report.examples[0].output;
    const raw: i48 = if (out.isInt()) out.asInt() else 0;
    const score: f32 = @as(f32, @floatFromInt(raw)) / 100.0;

    const feedback = feedbackFor(score);
    const verdict = eval_lib.Verdict{ .record = .{
        .evaluator_name = "judge",
        .score = score,
        .feedback = feedback,
    } };
    _ = verdict; // constructed for the demonstration; the curriculum
    // gates on the feedback STRING (the .record-only signal) rather
    // than on `passes(threshold)` since a scalar threshold can't
    // distinguish under-shoot from overshoot.

    // No-op iff the feedback says we're in the OK band.
    if (std.mem.eql(u8, feedback, "OK")) return;

    const cur: i48 = if (optimizer.state) |s| s.asInt() else 0;
    const delta: i48 = if (std.mem.eql(u8, feedback, "lower")) -5 else 5;
    optimizer.state = Value.makeInt(cur + delta);
}

test "feedbackFor: thresholds dispatch correctly" {
    try std.testing.expectEqualStrings("raise", feedbackFor(0.0));
    try std.testing.expectEqualStrings("raise", feedbackFor(0.5));
    try std.testing.expectEqualStrings("raise", feedbackFor(0.94));
    try std.testing.expectEqualStrings("OK", feedbackFor(0.95));
    try std.testing.expectEqualStrings("OK", feedbackFor(1.0));
    try std.testing.expectEqualStrings("lower", feedbackFor(1.05));
    try std.testing.expectEqualStrings("lower", feedbackFor(2.0));
}

test "Verdict.record carries score + feedback and projects via primaryScore" {
    const v = eval_lib.Verdict{ .record = .{
        .evaluator_name = "judge",
        .score = 0.85,
        .feedback = "raise",
    } };
    try std.testing.expectEqualStrings("judge", v.name());
    try std.testing.expectEqual(@as(f32, 0.85), v.primaryScore());
    try std.testing.expect(!v.passes(0.95));
    try std.testing.expect(v.passes(0.5));
}

test "Evaluator-Optimizer: bad seed (state=0) converges to score ≥ 0.95" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    _ = try topo.newAgent("optimizer", echoStateBody);
    topo.nodes.items[0].agent.state = Value.makeInt(0);

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "evopt");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "evopt", &topo, &trace_store, &ds, &evs, "optimizer");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = evalOptimizerStep } },
        .{ .iters = 30 },
        1,
        30,
    );
    defer traj.deinit();

    // Path: 0 → 5 → 10 → … → 95 → "OK" → no-op. Need 19 nudges; budget 30.
    const final: i48 = topo.nodes.items[0].agent.state.?.asInt();
    try std.testing.expect(final >= 95);
}

test "Evaluator-Optimizer: overshoot at score=1.05 triggers 'lower' feedback" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    _ = try topo.newAgent("optimizer", echoStateBody);
    // Seed at 110 → score 1.10. Should walk DOWN to 95–104 (the OK band).
    topo.nodes.items[0].agent.state = Value.makeInt(110);

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "over");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "over", &topo, &trace_store, &ds, &evs, "optimizer");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = evalOptimizerStep } },
        .{ .iters = 10 },
        1,
        10,
    );
    defer traj.deinit();

    const final: i48 = topo.nodes.items[0].agent.state.?.asInt();
    // Path: 110 (1.10 'lower') → 105 (1.05 'lower') → 100 (1.0 'OK') → no-op
    try std.testing.expect(final >= 95 and final < 105);
}

// ─────────────────────────────────────────────────────────────────────
// ProTeGi-coplay curriculum — Verdict.semantic exercised under
// Step.peer_pool (1-step beam search).
//
// Reference: Pryzant et al. 2023 (arXiv:2305.03495), "Automatic Prompt
// Optimization with 'Gradient Descent' and Beam Search". The original
// algorithm maintains a beam of prompt candidates and at each iteration
// expands each with LLM-generated textual gradients, then bandit-selects
// top-b. Here we encode the SHAPE without an LLM:
//
//   - Each peer is a candidate "edit" with a tagged semantic gradient
//     (string describing the mutation's intent).
//   - Each peer constructs a Verdict.semantic { gradient: <string> }
//     to prove the variant is wire-compatible with curriculum code,
//     even though peer_pool's selection uses the scalar pass_rate.
//   - peer_pool runs at frontier=peers.len; the highest-pass-rate peer
//     wins each iteration.
//
// What's missing vs full ProTeGi:
//   - No LLM-generated gradients (peers are hand-coded mutations).
//   - No persistent beam SET across iterations — each iter is a 1-step
//     beam (the current peer_pool semantics in cycle.zig).
//   - No bandit selection over candidates — strict argmax.
// All three would land if/when an LLM bridge appears in nanoclj-zig
// and cycle.zig grows persistent beam state. The curriculum here
// demonstrates the variant + step combo at fixed shape.
// ─────────────────────────────────────────────────────────────────────

const ProtegiPeer = struct {
    gradient: []const u8,
    delta: i48,
};

/// A peer's "semantic gradient" + the state delta it represents.
/// Defined as constants so each peer body can refer to its own
/// gradient text without runtime allocation.
const protegi_peer_inc_lo = ProtegiPeer{ .gradient = "raise low-order quality", .delta = 1 };
const protegi_peer_inc_hi = ProtegiPeer{ .gradient = "raise high-order quality", .delta = 10 };
const protegi_peer_dec_lo = ProtegiPeer{ .gradient = "trim low-order verbosity", .delta = -1 };
const protegi_peer_overshoot = ProtegiPeer{ .gradient = "double down on quality", .delta = 25 };

/// Construct the peer's Verdict.semantic and apply its state delta.
/// The verdict is constructed for protocol-validation (it appears in
/// real curriculum code) — peer_pool's scorer doesn't read it; that
/// role is reserved for a future Verdict.semantic-aware Evaluator.
fn applyProtegiPeer(experiment: *Experiment, peer: ProtegiPeer) !void {
    const optimizer = experiment.topology.getAgent("optimizer") orelse return;

    const verdict = eval_lib.Verdict{ .semantic = .{
        .evaluator_name = "protegi-grad",
        .gradient = peer.gradient,
    } };
    // Validate that the variant's dispatch methods work on this construction.
    if (!std.mem.eql(u8, verdict.name(), "protegi-grad")) return error.Invoke;
    // Verdict.semantic.passes() is unconditional true — the gradient
    // string itself is the revision direction; no scalar threshold.
    if (!verdict.passes(99.0)) return error.Invoke;

    const cur: i48 = if (optimizer.state) |s| s.asInt() else 0;
    optimizer.state = Value.makeInt(cur + peer.delta);
}

fn protegiPeerIncLo(experiment: *Experiment) anyerror!void {
    return applyProtegiPeer(experiment, protegi_peer_inc_lo);
}
fn protegiPeerIncHi(experiment: *Experiment) anyerror!void {
    return applyProtegiPeer(experiment, protegi_peer_inc_hi);
}
fn protegiPeerDecLo(experiment: *Experiment) anyerror!void {
    return applyProtegiPeer(experiment, protegi_peer_dec_lo);
}
fn protegiPeerOvershoot(experiment: *Experiment) anyerror!void {
    return applyProtegiPeer(experiment, protegi_peer_overshoot);
}

test "Verdict.semantic: dispatch methods round-trip through curriculum constructors" {
    const v = eval_lib.Verdict{ .semantic = .{
        .evaluator_name = "protegi-grad",
        .gradient = "raise high-order quality",
    } };
    try std.testing.expectEqualStrings("protegi-grad", v.name());
    try std.testing.expectEqual(@as(f32, 0.0), v.primaryScore());
    try std.testing.expect(v.passes(0.0));
    try std.testing.expect(v.passes(99.0)); // semantic always passes
}

fn passAt10Scorer(v: Value) eval_lib.EvalError!f32 {
    // Score = state - 10. Pass when state >= 11 (score > 0). Negative
    // overshoot at state >> 10 still passes; the test below uses a
    // pass_rate threshold to stop at the first peer that lands all
    // examples positive.
    return @as(f32, @floatFromInt(v.asInt())) - 10.0;
}

test "ProTeGi-coplay: peer_pool selects the smallest-delta peer that achieves 100% pass" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();

    _ = try topo.newAgent("optimizer", echoStateBody);
    topo.nodes.items[0].agent.state = Value.makeInt(0); // bad seed

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "protegi");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("scoreAt10", passAt10Scorer)};
    var exp = Experiment.init(std.testing.allocator, "protegi", &topo, &trace_store, &ds, &evs, "optimizer");

    const peers = [_]cycle_lib.Step.PeerFn{
        protegiPeerIncLo, // +1
        protegiPeerIncHi, // +10
        protegiPeerDecLo, // -1
        protegiPeerOvershoot, // +25
    };

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .peer_pool = .{ .peers = &peers } },
        .{ .iters = 3 },
        1,
        3,
    );
    defer traj.deinit();

    // iter 0: state=0 (no pass). Peers try state=1, 10, -1, 25.
    //   pass_rate at each: 1→fail, 10→fail (score=0, not >0), -1→fail,
    //   25→pass(rate=1.0). Overshoot wins → state=25.
    // iter 1: state=25. All four peers reach pass_rate=1.0; ties → first
    //   peer (+1) wins → state=26.
    // iter 2: state=26 (run, no further step).
    try std.testing.expectEqual(@as(u32, 3), traj.iterations);
    const final_state = topo.nodes.items[0].agent.state.?.asInt();
    try std.testing.expectEqual(@as(i48, 26), final_state);
    try std.testing.expectEqual(@as(f32, 1.0), traj.passRate());
}

test "ProTeGi-coplay: every peer body successfully constructs Verdict.semantic" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    _ = try topo.newAgent("optimizer", echoStateBody);
    topo.nodes.items[0].agent.state = Value.makeInt(0);

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "smoke");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");
    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "smoke", &topo, &trace_store, &ds, &evs, "optimizer");

    // Each peer body internally errors if the Verdict.semantic dispatch
    // breaks. Calling them all proves the construction is sound.
    try protegiPeerIncLo(&exp);
    try protegiPeerIncHi(&exp);
    try protegiPeerDecLo(&exp);
    try protegiPeerOvershoot(&exp);

    // Net effect: 0 +1 +10 -1 +25 = 35
    try std.testing.expectEqual(@as(i48, 35), topo.nodes.items[0].agent.state.?.asInt());
}

test "Solo-MAGICORE: refiner is a no-op on already-perfect chain" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();

    _ = try topo.newAgent("solver", echoStateBody);
    topo.nodes.items[0].agent.state = Value.makeInt(99999);

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "perfect");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "perfect", &topo, &trace_store, &ds, &evs, "solver");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = magicoreRefineStep } },
        .{ .iters = 5 },
        1,
        5,
    );
    defer traj.deinit();

    try std.testing.expectEqual(@as(i48, 99999), topo.nodes.items[0].agent.state.?.asInt());
}
