//! Law-merged Nash curriculum — first concrete curriculum landing on
//! the §6 SDF stack (Skill registry + Verdict union + cycle combinator).
//!
//! Categorical anchor:
//!   `goblins-adapter/propagator-nash.scm:140` — `merge-with-law`:
//!     `Merge × Law → Merge'`.
//!   Wraps a base merge so any law-violating outcome promotes to a
//!   contradiction. Here the merge IS the cycle's Step (which mutates
//!   agent state) and the law is GF(3) closure on the strategy trits.
//!
//! Setup:
//!   - N agents each carry an i48 `state` interpreted as their proposed
//!     strategy. Their body just echoes that state (the topology runs;
//!     the evaluator is satisfied by an always-positive scorer; the
//!     point of the curriculum is the inter-iteration STEP, not the
//!     evaluator output).
//!
//!   - The `lawMergeStep` body collects every agent's `(state mod 3)`
//!     trit, checks GF(3) closure (sum ≡ 0 mod 3). If the law holds,
//!     it's a no-op (the topology has reached a Nash-stable lawful
//!     point). If violated, it nudges the last agent's state +1; this
//!     is guaranteed to land on a lawful triad within ≤2 nudges for
//!     three agents (the cyclic group GF(3) is generated by +1).
//!
//! That is the SDF-permanent-extension promise paying off:
//!   - Step.custom (§6.3) gives us the structural mutation hook.
//!   - The curriculum lives in its own file with no edits to feedback.zig
//!     / cycle.zig / experiment.zig.
//!   - Adding ProTeGi-coplay or Solo-MAGICORE later follows the same
//!     pattern: another submodule, another `*Step.body` closure.

const std = @import("std");
const value = @import("../value.zig");
const Value = value.Value;

const agent_lib = @import("agent.zig");
const eval_lib = @import("eval.zig");
const dataset_lib = @import("dataset.zig");
const experiment_lib = @import("experiment.zig");
const topology_lib = @import("topology.zig");
const trace_lib = @import("trace.zig");
const cycle_lib = @import("cycle.zig");

const Topology = topology_lib.Topology;
const Experiment = experiment_lib.Experiment;
const Report = experiment_lib.Report;

/// Project an agent's i48 state to a GF(3) trit ∈ {-1, 0, +1}, matching
/// `Verdict.trit`'s `i2` convention. `state mod 3 = 2` collapses onto
/// `-1` since `2 ≡ -1 (mod 3)` in the GF(3) signed representation.
pub fn stateToTrit(state: ?Value) i2 {
    const s: i48 = if (state) |v| v.asInt() else 0;
    const m: i48 = @mod(s, 3); // 0, 1, or 2
    return switch (m) {
        0 => 0,
        1 => 1,
        2 => -1,
        else => unreachable,
    };
}

/// GF(3) closure check: sum of trits ≡ 0 (mod 3).
pub fn lawHolds(trits: []const i2) bool {
    var sum: i32 = 0;
    for (trits) |t| sum += @as(i32, t);
    return @mod(sum, 3) == 0;
}

/// The `cycle.Step.custom.body` for this curriculum.
/// Reads every agent's state, projects to GF(3) trit, checks the law;
/// if violated, nudges the last agent's state by +1 to walk toward
/// closure. (No-op when already lawful — that's the fixed point.)
pub fn lawMergeStep(experiment: *Experiment, _: *const Report) anyerror!void {
    const topo = experiment.topology;
    const n = topo.nodes.items.len;
    if (n == 0) return;

    var trits: std.ArrayListUnmanaged(i2) = .empty;
    defer trits.deinit(experiment.allocator);
    for (topo.nodes.items) |*node| {
        try trits.append(experiment.allocator, stateToTrit(node.agent.state));
    }
    if (lawHolds(trits.items)) return;

    const last = &topo.nodes.items[n - 1].agent;
    const cur: i48 = if (last.state) |v| v.asInt() else 0;
    last.state = Value.makeInt(cur + 1);
}

// ─────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────

fn echoStateBody(ctx: *agent_lib.Agent, _: Value) error{Invoke}!Value {
    if (ctx.state) |s| return s;
    return Value.makeInt(0);
}

fn alwaysPositiveScorer(_: Value) eval_lib.EvalError!f32 {
    return 1.0;
}

test "stateToTrit: null → 0; 1 → 1; 5 → -1 (2≡-1); 9 → 0" {
    try std.testing.expectEqual(@as(i2, 0), stateToTrit(null));
    try std.testing.expectEqual(@as(i2, 1), stateToTrit(Value.makeInt(1)));
    try std.testing.expectEqual(@as(i2, -1), stateToTrit(Value.makeInt(5)));
    try std.testing.expectEqual(@as(i2, 0), stateToTrit(Value.makeInt(9)));
}

test "lawHolds: 1+1+1 ≡ 0 (mod 3)" {
    const trits = [_]i2{ 1, 1, 1 };
    try std.testing.expect(lawHolds(&trits));
}

test "lawHolds: 0+0+0 ≡ 0" {
    const trits = [_]i2{ 0, 0, 0 };
    try std.testing.expect(lawHolds(&trits));
}

test "lawHolds: 0+1+(-1) ≡ 0 (≡ 0+1+2 in unsigned mod-3)" {
    const trits = [_]i2{ 0, 1, -1 };
    try std.testing.expect(lawHolds(&trits));
}

test "lawHolds: 1+1+0 ≢ 0" {
    const trits = [_]i2{ 1, 1, 0 };
    try std.testing.expect(!lawHolds(&trits));
}

fn setupThreeAgentExperiment(
    topo: *Topology,
    trace_store: *trace_lib.TraceStore,
    ds: *dataset_lib.Dataset,
    seeds: [3]i48,
) !void {
    const id_a = try topo.newAgent("a", echoStateBody);
    const id_b = try topo.newAgent("b", echoStateBody);
    const id_c = try topo.newAgent("c", echoStateBody);
    topo.nodes.items[id_a - 1].agent.state = Value.makeInt(seeds[0]);
    topo.nodes.items[id_b - 1].agent.state = Value.makeInt(seeds[1]);
    topo.nodes.items[id_c - 1].agent.state = Value.makeInt(seeds[2]);
    try ds.addExample(Value.makeInt(0), null, "");
    _ = trace_store;
}

test "law-merged Nash: balanced seed (1,1,1) is already a fixed point" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    var ds = dataset_lib.Dataset.init(std.testing.allocator, "balanced");
    defer ds.deinit();
    try setupThreeAgentExperiment(&topo, &trace_store, &ds, .{ 1, 1, 1 });

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "balanced", &topo, &trace_store, &ds, &evs, "a");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = lawMergeStep } },
        .{ .iters = 5 },
        1,
        5,
    );
    defer traj.deinit();

    // No-op step → c remains at 1.
    try std.testing.expectEqual(@as(i48, 1), topo.nodes.items[2].agent.state.?.asInt());
    // GF(3) law still holds.
    var trits: [3]i2 = undefined;
    for (topo.nodes.items, 0..) |node, i| trits[i] = stateToTrit(node.agent.state);
    try std.testing.expect(lawHolds(&trits));
}

test "law-merged Nash: imbalanced (1,0,0) converges to a lawful triad" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    var ds = dataset_lib.Dataset.init(std.testing.allocator, "imbalanced");
    defer ds.deinit();
    try setupThreeAgentExperiment(&topo, &trace_store, &ds, .{ 1, 0, 0 });

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "imbalanced", &topo, &trace_store, &ds, &evs, "a");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = lawMergeStep } },
        .{ .iters = 10 },
        1,
        10,
    );
    defer traj.deinit();

    // After enough custom-step nudges the GF(3) law holds.
    var trits: [3]i2 = undefined;
    for (topo.nodes.items, 0..) |node, i| trits[i] = stateToTrit(node.agent.state);
    try std.testing.expect(lawHolds(&trits));
    // a stayed at 1 (it's not the last agent); b stayed at 0; c was nudged.
    try std.testing.expectEqual(@as(i48, 1), topo.nodes.items[0].agent.state.?.asInt());
    try std.testing.expectEqual(@as(i48, 0), topo.nodes.items[1].agent.state.?.asInt());
    // c's trit must close the law: trits[0]=1, trits[1]=0 ⇒ trit[2]=-1
    // (equivalently, c.state mod 3 = 2).
    try std.testing.expectEqual(@as(i2, -1), stateToTrit(topo.nodes.items[2].agent.state));
}

test "law-merged Nash: imbalanced (2,2,0) converges by nudging c twice" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();
    var ds = dataset_lib.Dataset.init(std.testing.allocator, "twos");
    defer ds.deinit();
    try setupThreeAgentExperiment(&topo, &trace_store, &ds, .{ 2, 2, 0 });
    // a.state=2 → trit -1; b.state=2 → trit -1; c.state=0 → trit 0.
    // Sum = -2 ≡ 1 (mod 3) ≢ 0. Need c's trit such that -1 + -1 + t ≡ 0
    // ⇒ t ≡ -1. Starting c=0, two nudges → c=2 → trit -1. ✓

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "twos", &topo, &trace_store, &ds, &evs, "a");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = lawMergeStep } },
        .{ .iters = 10 },
        1,
        10,
    );
    defer traj.deinit();

    var trits: [3]i2 = undefined;
    for (topo.nodes.items, 0..) |node, i| trits[i] = stateToTrit(node.agent.state);
    try std.testing.expect(lawHolds(&trits));
    try std.testing.expectEqual(@as(i2, -1), stateToTrit(topo.nodes.items[2].agent.state));
}

// ─────────────────────────────────────────────────────────────────────
// Solo-MAGICORE curriculum — Solver/Reviewer/Refiner triad with
// step-wise PRM scoring via Verdict.vector.
//
// Reference: Sachin Kumar et al. 2024, "MAGICORE: Multi-Agent Iteration
// for Coarse-to-fine Refinement". Three-agent feedback loop where:
//   - Solver  produces a k-step reasoning chain
//   - Reviewer scores each step (PRM = process reward model)
//   - Refiner uses the per-step scores to decide which step to fix
//
// Concrete Zig encoding without an LLM:
//   - "Chain" = an i48 state interpreted as a 5-digit decimal value
//   - "PRM"   = digitwise scorer; each digit's score = digit / 9.0,
//               so high digits (closer to 9) mean "high quality step"
//   - "Refiner" = the Step.custom body that increments the
//                 lowest-scoring digit's "place value" until the chain's
//                 minimum digit clears the threshold
//
// The curriculum demonstrates Verdict.vector being constructed in
// real curriculum code and dispatched through `primaryScore()` (which
// projects the vector to its mean for legacy passes). The refiner
// reads the raw vector to do step-wise repair, not just mean-based
// gating — that's the whole point of MAGICORE over a scalar reward.
// ─────────────────────────────────────────────────────────────────────

/// Decompose an i48 chain into 5 digits, MSB first. State outside
/// [0, 99999] is clamped to [0, 99999].
pub fn chainDigits(state: ?Value) [5]u8 {
    const s_raw: i48 = if (state) |v| v.asInt() else 0;
    var s: i48 = if (s_raw < 0) 0 else if (s_raw > 99999) 99999 else s_raw;
    var out: [5]u8 = .{ 0, 0, 0, 0, 0 };
    var i: usize = 5;
    while (i > 0) {
        i -= 1;
        out[i] = @intCast(@mod(s, 10));
        s = @divFloor(s, 10);
    }
    return out;
}

/// PRM (process reward model): each digit's reward = digit / 9.0 ∈ [0, 1].
/// Returns a Verdict.vector whose `steps` borrow `out_buf` — caller owns
/// the buffer and must keep it alive while the verdict is examined.
pub fn digitwisePRM(state: ?Value, name: []const u8, out_buf: *[5]f32) eval_lib.Verdict {
    const digits = chainDigits(state);
    for (digits, 0..) |d, i| {
        out_buf[i] = @as(f32, @floatFromInt(d)) / 9.0;
    }
    return .{ .vector = .{
        .evaluator_name = name,
        .steps = out_buf[0..],
    } };
}

/// Refiner step: read the solver's current chain, score each digit
/// via the PRM, find the worst-scoring digit, and bump that place's
/// value by +1 in the i48 state. Stops being a no-op once every
/// digit's score ≥ 7/9 ≈ 0.78 (i.e., every digit is ≥ 7).
pub fn magicoreRefineStep(experiment: *Experiment, _: *const Report) anyerror!void {
    const topo = experiment.topology;
    const solver = topo.getAgent("solver") orelse return;

    var scores: [5]f32 = undefined;
    const verdict = digitwisePRM(solver.state, "prm", &scores);

    // primaryScore() = mean of vector; cycle stop predicates can use it.
    // Here we use the raw steps for the refiner decision.
    const v = verdict.vector;
    var worst_idx: usize = 0;
    var worst_score: f32 = v.steps[0];
    for (v.steps[1..], 1..) |s, i| {
        if (s < worst_score) {
            worst_score = s;
            worst_idx = i;
        }
    }
    if (worst_score >= 7.0 / 9.0) return; // already at fixed point

    // Place value of digit at index worst_idx (MSB=0): 10^(4-worst_idx).
    const place: i48 = std.math.pow(i48, 10, @intCast(4 - worst_idx));
    const cur: i48 = if (solver.state) |s| s.asInt() else 0;
    solver.state = Value.makeInt(cur + place);
}

test "chainDigits decomposes 12345 → [1,2,3,4,5]" {
    const d = chainDigits(Value.makeInt(12345));
    try std.testing.expectEqualSlices(u8, &.{ 1, 2, 3, 4, 5 }, &d);
}

test "chainDigits clamps negatives to zero, large to 99999" {
    try std.testing.expectEqualSlices(u8, &.{ 0, 0, 0, 0, 0 }, &chainDigits(Value.makeInt(-7)));
    try std.testing.expectEqualSlices(u8, &.{ 9, 9, 9, 9, 9 }, &chainDigits(Value.makeInt(123456789)));
}

test "digitwisePRM yields Verdict.vector with per-digit reward" {
    var buf: [5]f32 = undefined;
    const v = digitwisePRM(Value.makeInt(99999), "prm", &buf);
    try std.testing.expectEqualStrings("prm", v.name());
    // primaryScore is mean-of-steps; 9/9 averaged = 1.0
    try std.testing.expectApproxEqAbs(@as(f32, 1.0), v.primaryScore(), 1e-6);
    // mean of zero digits = 0
    var buf2: [5]f32 = undefined;
    const v2 = digitwisePRM(Value.makeInt(0), "prm", &buf2);
    try std.testing.expectEqual(@as(f32, 0.0), v2.primaryScore());
}

test "Solo-MAGICORE: refiner converges to all-7+ chain" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();

    _ = try topo.newAgent("solver", echoStateBody);
    _ = try topo.newAgent("reviewer", echoStateBody);
    _ = try topo.newAgent("refiner", echoStateBody);
    try topo.connect("solver", "reviewer");
    try topo.connect("reviewer", "refiner");

    // Seed: 11111 → digits [1,1,1,1,1], all scores 1/9. Worst=any; refiner
    // bumps a place each iter. Needs ~5 nudges per place × (7-1) bump =
    // 30+ iters. Give it 60 to converge.
    topo.nodes.items[0].agent.state = Value.makeInt(11111);

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "magicore");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "magicore", &topo, &trace_store, &ds, &evs, "solver");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = magicoreRefineStep } },
        .{ .iters = 60 },
        1,
        60,
    );
    defer traj.deinit();

    // After convergence, every digit of solver.state should be ≥ 7.
    const final_state = topo.nodes.items[0].agent.state.?;
    const digits = chainDigits(final_state);
    for (digits) |d| try std.testing.expect(d >= 7);
}

test "Solo-MAGICORE: refiner is a no-op on already-perfect chain" {
    var topo = Topology.init(std.testing.allocator);
    defer topo.deinit();
    var trace_store = trace_lib.TraceStore.init(std.testing.allocator);
    defer trace_store.deinit();

    _ = try topo.newAgent("solver", echoStateBody);
    topo.nodes.items[0].agent.state = Value.makeInt(99999);

    var ds = dataset_lib.Dataset.init(std.testing.allocator, "perfect");
    defer ds.deinit();
    try ds.addExample(Value.makeInt(0), null, "");

    const evs = [_]eval_lib.Evaluator{eval_lib.individual("ok", alwaysPositiveScorer)};
    var exp = Experiment.init(std.testing.allocator, "perfect", &topo, &trace_store, &ds, &evs, "solver");

    var traj = try cycle_lib.cycle(
        std.testing.allocator,
        &exp,
        .{ .custom = .{ .body = magicoreRefineStep } },
        .{ .iters = 5 },
        1,
        5,
    );
    defer traj.deinit();

    try std.testing.expectEqual(@as(i48, 99999), topo.nodes.items[0].agent.state.?.asInt());
}
