(do
(def cc (fn [n r] (if (< r 5) (str n "++") (if (< r 50) (str n "~~") (str n "XX")))))
(def tr (fn [r] (if (< r 5) "G" (if (< r 50) "Y" "R"))))
(println "  GEODESIC 16ch | 252K | Cyton+Daisy 125Hz")
(println "  ++ clean  ~~ flicker  XX rail")
(println "                    nasion")
(println (str "               " (cc "Fp1" 100) "     " (cc "Fp2" 0)))
(println "                / \\     / \\")
(println (str "          " (cc "F7 " 100) " " (cc "F3 " 100) "       " (cc "F4 " 100) " " (cc "F8 " 100)))
(println "            |  / \\       / \\  |")
(println (str "     L   " (cc "T7 " 0) " " (cc "C3 " 7) "   Cz   " (cc "C4 " 0) " " (cc "T8 " 100) "   R"))
(println "            |  \\ /       \\ /  |")
(println (str "          " (cc "P7 " 100) " " (cc "P3 " 0) "       " (cc "P4 " 100) " " (cc "P8 " 100)))
(println "                \\ /     \\ /")
(println (str "               " (cc "O1 " 0) "     " (cc "O2 " 100)))
(println "                    inion")
(println (str "  GF(3) " (tr 100) (tr 0) (tr 7) (tr 0) (tr 100) (tr 100) (tr 0) (tr 100) (tr 100) (tr 100) (tr 100) (tr 100) (tr 0) (tr 100) (tr 0) (tr 100)))
(println "  Clean:5/16 Rail:11/16 sum=-6 bci.blue:tileable")
)
