(do
(def cc (fn [n r] (if (< r 5) (str n "++") (if (< r 50) (str n "~~") (str n "XX")))))
(def tr (fn [r] (if (< r 5) 0 (if (< r 50) 1 -1))))
(def rv [100 0 7 0 100 100 0 100 100 100 100 100 0 100 0 100])
(def r (fn [i] (nth rv i)))
(def ts (fn [i a] (if (>= i 16) a (recur (+ i 1) (+ a (tr (r i)))))))
(def gf3 (ts 0 0))
(println "  GEODESIC 16ch | 252K samples | Cyton+Daisy 125Hz")
(println "  ++ clean  ~~ flicker  XX rail")
(println "                    nasion")
(println (str "               " (cc "Fp1" (r 0)) "     " (cc "Fp2" (r 1))))
(println "                / \\     / \\")
(println (str "          " (cc "F7 " (r 8)) " " (cc "F3 " (r 10)) "       " (cc "F4 " (r 11)) " " (cc "F8 " (r 9))))
(println "            |  / \\       / \\  |")
(println (str "     L   " (cc "T7 " (r 12)) " " (cc "C3 " (r 2)) "   Cz   " (cc "C4 " (r 3)) " " (cc "T8 " (r 13)) "   R"))
(println "            |  \\ /       \\ /  |")
(println (str "          " (cc "P7 " (r 4)) " " (cc "P3 " (r 14)) "       " (cc "P4 " (r 15)) " " (cc "P8 " (r 5))))
(println "                \\ /     \\ /")
(println (str "               " (cc "O1 " (r 6)) "     " (cc "O2 " (r 7))))
(println "                    inion")
(def tw (fn [i a] (if (>= i 16) a (recur (+ i 1) (str a (if (< (r i) 5) "G" (if (< (r i) 50) "Y" "R")))))))
(println (str "  GF(3): " (tw 0 "") " sum=" gf3))
(def nc (fn [i a] (if (>= i 16) a (recur (+ i 1) (if (< (r i) 5) (+ a 1) a)))))
(println (str "  Clean:" (nc 0 0) "/16 Rail:" (- 16 (nc 0 0)) "/16"))
(println "  bci.blue: each electrode = GF(3) cell in tileable automaton")
)
