(do

(def cc (fn [n r]
  (if (< r 5)
    (str n "++")
    (if (< r 50)
      (str n "~~")
      (str n "XX")))))

(println "")
(println "  GEODESIC 16ch 10-20 HEAD MAP  Cyton+Daisy 125Hz")
(println "  ++ = clean    ~~ = flicker    XX = railing")
(println "")
(println "                    nasion")
(println (str "               " (cc "Fp1" 0)   "     " (cc "Fp2" 0)))
(println "                / \\     / \\")
(println (str "          " (cc "F7 " 100) " " (cc "F3 " 100) "       " (cc "F4 " 100) " " (cc "F8 " 56)))
(println "            |  / \\       / \\  |")
(println (str "     L   " (cc "T7 " 0) " " (cc "C3 " 100) "   Cz   " (cc "C4 " 0) " " (cc "T8 " 100) "   R"))
(println "            |  \\ /       \\ /  |")
(println (str "          " (cc "P7 " 100) " " (cc "P3 " 0)   "       " (cc "P4 " 100) " " (cc "P8 " 0)))
(println "                \\ /     \\ /")
(println (str "               " (cc "O1 " 100) "     " (cc "O2 " 100)))
(println "                    inion")
(println "")
(println "  SUMMARY")
(println "  Clean (6):  Fp1 Fp2 C4 P8 T7 P3")
(println "  Flick (0):  (none currently, F8 was 56% last epoch)")
(println "  Rail (10):  C3 P7 O1 O2 F7 F8 F3 F4 T8 P4")
(println "")
(println "  Cyton ch1-8:   Fp1++ Fp2++ C3XX C4++ P7XX P8++ O1XX O2XX")
(println "  Daisy ch9-16:  F7XX  F8~~  F3XX F4XX T7++ T8XX P3++ P4XX")

)
